mysite/myapp/urls.py
from django.urls import path
import myapp.views as views


app_name = "myapp"
urlpatterns = [
    # path("", views.index, name='index'),
    path("", views.ProductListView.as_view(), name='index'),
    # path("<int:correct_product_id>/", views.index_item, name="detail"),
    path("<int:pk>/", views.ProductDetailView.as_view(), name="detail"),
    path("add_item/", views.add_item, name="add_item"),
    path("update_item/<int:correct_product_id>", views.update_item, name="update_item"),
    path("delete_item/<int:correct_product_id>", views.delete_item, name="delete_item"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/', include('myapp.urls', namespace='myapp')),
    path('users/', include('users.urls', namespace='users')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
import users.views as views


app_name = "users"

urlpatterns = [
    path("register/", views.register, name="register"),
    path("login/", LoginView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", LogoutView.as_view(template_name='users/logout.html'), name="logout"),
    path("profile/", views.profile, name="profile"),
    path("seller_profile/<int:id>/", views.seller_profile, name="seller_profile"),
]

mysite/myapp/models.py
from django.db import models
from django.contrib.auth.models import User


class Product(models.Model):
    name = models.CharField(max_length=100)
    price = models.IntegerField()
    description = models.CharField(max_length=200)
    image = models.ImageField(blank=True, upload_to='images')

    def __str__(self):
        return self.name

mysite/users/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(blank=True, upload_to='profile_images')
    contact_numer = models.CharField(max_length=20, default='+7(988)-***-**-**')

    def __str__(self):
        return self.user.username

mysite/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms


class NewUserForm(UserCreationForm):
    email = forms.EmailField(
        required=True,
        widget=forms.EmailInput(
            attrs={
                "class": "focus:outline-none",
                "placeholder": "mail@mail.ru"
            }))
    username = forms.CharField(
        required=True,
        widget=forms.TextInput(
            attrs={
                "class": "focus:outline-none",
                "placeholder": "Enter username"
            }))
    password1 = forms.CharField(
        required=True,
        widget=forms.PasswordInput(
            attrs={
                "class": "focus:outline-none",
                "placeholder": "Enter password"
            }))
    password2 = forms.CharField(
        required=True,
        widget=forms.PasswordInput(
            attrs={
                "class": "focus:outline-none",
                "placeholder": "Confirm password"
            }))

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    # def save(self, commit=True):
    #     user = super(NewUserForm, self).save(commit=False)
    #     user.email = self.cleaned_data['email']
    #     if commit:
    #         user.save()
    #     return user

mysite/myapp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, DetailView
from .models import Product


# def index(request):
#     items = Product.objects.all()
#     context = {"items": items,}
#     return render(request, "myapp/index.html", context)


class ProductListView(ListView):
    model = Product
    template_name = "myapp/index.html"
    context_object_name = "items"


# def index_item(request, correct_product_id):
#     item = Product.objects.get(id=correct_product_id)
#     context = {"item": item,}
#     return render(request, "myapp/detail.html", context)


class ProductDetailView(DetailView):
    model = Product
    template_name = "myapp/detail.html"
    context_object_name = "item"

@login_required
def add_item(request):
    if request.method == "POST":
        name = request.POST.get("name")
        price = request.POST.get("price")
        description = request.POST.get("description")
        image = request.FILES.get("upload")
        item = Product(name=name, price=price, description=description, image=image)
        item.save()
    return render(request, "myapp/add_item.html")


def update_item(request, correct_product_id):
    item = Product.objects.get(id=correct_product_id)

    if request.method == "POST":
        item.name = request.POST.get("name")
        item.price = request.POST.get("price")
        item.description = request.POST.get("description")
        item.image = request.FILES.get("upload", item.image)
        item.save()
        return redirect("/myapp/")
    context = {"item": item}
    return render(request, "myapp/update_item.html", context)


def delete_item(request, correct_product_id):
    item = Product.objects.get(id=correct_product_id)

    if request.method == "POST":
        item.delete()
        return redirect("/myapp/")

    context = {"item": item}
    return render(request, "myapp/delete_item.html", context)

mysite/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .forms import NewUserForm
from .models import Profile


def register(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("myapp:index")
    form = NewUserForm()
    context = {"form": form}
    return render(request, "users/register.html", context)


@login_required
def profile(request):
    if request.method == "POST":
        contact_numer = request.POST.get("number")
        image = request.FILES["upload"]
        user = request.user
        profile = Profile(user=user, contact_numer=contact_numer, image=image)
        profile.save()
    return render(request, "users/profile.html")


def seller_profile(request, id):
    seller = User.objects.get(id=id)
    context = {"seller": seller}
    return render(request, "users/seller_profile.html", context)

mysite/myapp/templates/myapp/add_item.html
{% extends "myapp/base.html" %}
{% block content %}
<div class="ml-[200px]">
    <h1 class="text-2xl m-10 font-bold text-green-600">Add New Item Below</h1>
    <form class="w-1/3 bg-white shadow-md m-10 px-8 py-8" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-4">
            <label class="block text-gray-700 text-md font-bold mb-2" for="name">Item Name</label>
            <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" type="text" placeholder="Name..." name="name" id="name">
            <label class="block text-gray-700 text-md font-bold mb-2 mt-2" for="price">Item Price</label>
            <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" type="text" placeholder="Price..." name="price" id="price">
            <label class="block text-gray-700 text-md font-bold mb-2 mt-2" for="description">Item Description</label>
            <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" type="text" placeholder="Description..." name="description" id="description">
            <input class="block mt-4" type="file" accept="image/*" name="upload" id="upload">
            <button class="block bg-green-600 text-white p-3 mt-4" type="submit" name="Add Item" value="Add Item">Add Item</button>
        </div>
    </form>
</div>
{% endblock content %}

mysite/myapp/templates/myapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'myapp/styles.css' %}">
    <link rel="shortcut icon" href="#">
</head>
<body>
    {% include "myapp/navbar.html" %}
    {% block content %}
    {% endblock content %}
</body>
</html>

mysite/myapp/templates/myapp/delete_item.html
{% extends "myapp/base.html" %}

{% block content %}
  <h1 class="text-2xl m-10 font bold">Delete Product</h1>
  <form class="bg-white shadow-md m-10 w-3/5 rounded px-8 pt-6 pb-8 mb-4" method="post">
    {% csrf_token %}
    <div class="mb-4">
      <label class="block text-gray text-sm font mb-2">Are you sure?</label>
      <label class="block text-gray text-sm font mb-2">{{ item.name }}</label>
      <img class="w-40 h-40" src="{{ item.image.url }}">
    </div>
    <input class="bg-red-500 text-white px-5 py-2" type="submit" value="Confirm">
    <a class="button bg-green-500 text-white px-5 py-3" href="{% url 'myapp:index' %}">Cancel</a>
  </form>
{% endblock content %}

mysite/myapp/templates/myapp/detail.html
{% extends "myapp/base.html" %}
{% load humanize %}

{% block content %}
    <div class="flex p-10 w-full h-200">
        <img class="w-1/3" src="{{ item.image.url }}" alt="">
        <div class="w-2/3 text-xl ml-10 mt-5">
            <p class="mt-5 ">{{ item.name }}</p>
            <p class="mt-5 text-green-500">{{ item.price | intcomma }} р.</p>
            <p class="mt-5 text-gray-600">{{ item.description }}
            <button class="bg-green-500 text-white mt-[50px]"><a href="{% url 'myapp:update_item' item.id %}">Update Item</a></button>
            <button class="bg-red-500 text-white mt-[50px]"><a href="{% url 'myapp:delete_item' item.id %}">Delete Item</a></button>
        </div>
    </div>
{% endblock content %}

mysite/myapp/templates/myapp/index.html
{% extends "myapp/base.html" %}
{% block content %}
<main class="mt-10 mx-auto max-w-7xl px-4 sm:mt-12 sm:px-6 md:mt-16 lg:mt-20 lg:px-8 xl:mt-28">
    <div class="sm:text-center lg:text-left">
        <h1 class="text-4xl font-extrabold text-gray-900 sm:text-5xl md:text-6xl">
            <span class="block xl:inline">Эксклюзивные Товары</span><br>
            <span class="block xl:inline text-green-500">По Отличным Ценам</span>
        </h1>
        <p class="mt-3 text-base text-gray-500 sm:mt-5 sm:text-lg sm:max-w-xl sm:mx-auto md:mt-5 md:text-xl lg:mx-0">Вы можете заказать товар из любой точки мира. Доставка включена</p>
    </div>
<div class="p-10 grid grid-cols-1 sm:grid-cols-1 md:grid-cols-3 xl:grid-col-3 lg:grid-col-3 gap-3">
    {% for item in items %}
        <a href="{% url 'myapp:detail' item.id %}">
            <div class="rounded overflow-hidden shadow-lg">
                <img class="w-full h-[400px]" src="{{ item.image.url }}">
                <div class="px-6 py-4">
                    <p class="font-bold text-xl mb-2">{{ item.name }}</p>
                    <p class="font-bold text-xl text-green-500 mb-2">{{ item.price }} р.</p>
                    <p class="text-gray-700 text-base">{{ item.description }}</p>
                </div>
            </div>
        </a>
    {% endfor %}
</div>
</main>
{% endblock content %}

mysite/myapp/templates/myapp/navbar.html
{% load static %}
<nav class="bg-white shadow-lg">
        <div class="max-w-6xl mx-auto px-4">
            <div class="flex justify-between">
                <div class="flex space-x-7">
                    <div>
                        <a href="{% url 'myapp:index' %}" class="flex items-center px-2 py-4">
                            <img class="h-8 w-8" src="{% static 'myapp/images/shopping-cart.png' %}" alt="logo">
                            <span class="text-gray-500 font-semibold text-xl">Pro Shop</span>
                        </a>
                    </div>
                    <div class="items-center flex space-x-1">
                        <a href="{% url 'myapp:index' %}" class="py-4 px-2 text-gray-500 font-semibold border-b-4 border-green-500">Home</a>
                        <a href="{% url 'myapp:add_item' %}" class="py-4 px-2 text-gray-500 font-semibold">Add Item</a>
                        <a href="#" class="py-4 px-2 text-gray-500 font-semibold">Contacts</a>
                        {% if user.is_authenticated %}
                            <a href="{% url 'users:logout' %}" class="py-4 px-2 text-gray-500 font-semibold">Log Out</a>
                            <a href="{% url 'users:profile' %}" class="py-4 px-2 text-gray-500 font-semibold">Profile</a>
                        {% else %}
                            <a href="{% url 'users:login' %}" class="py-4 px-2 text-gray-500 font-semibold">Log In</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </nav>

mysite/myapp/templates/myapp/update_item.html
{% extends "myapp/base.html" %}
{% block content %}
<div class="ml-[200px]">
    <h1 class="text-2xl m-10 font-bold text-green-600">Update Item</h1>
    <form class="w-1/3 bg-white shadow-md m-10 px-8 py-8" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-4">
            <label class="block text-gray-700 text-md font-bold mb-2" for="name">Item Name</label>
            <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" value="{{ item.name }}" type="text" placeholder="Name..." name="name" id="name">
            <label class="block text-gray-700 text-md font-bold mb-2 mt-2" for="price">Item Price</label>
            <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" value="{{ item.price }}" type="text" placeholder="Price..." name="price" id="price">
            <label class="block text-gray-700 text-md font-bold mb-2 mt-2" for="description">Item Description</label>
            <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" value="{{ item.description }}" type="text" placeholder="Description..." name="description" id="description">
            <img class="w-20 h-20 m-4" src="{{ item.image.url }}">
            <input class="block mt-4" type="file" accept="image/*" name="upload" id="upload">
            <button class="block bg-green-600 text-white p-3 mt-4" type="submit" name="Add Item" value="Add Item">Update Item</button>
        </div>
    </form>
</div>
{% endblock content %}

mysite/users/templates/seller_profile.html
{% extends "myapp/base.html" %}

{% block content %}
    <h1>Seller Profile</h1>
{% endblock content %}

mysite/users/templates/users/login.html
{% extends "myapp/base.html" %}

{% block content %}
  <div class="container py-5">
    <h1 class="text-2xl m-10 font-bold">Login User</h1>
    <form class="w-2/5 bg-white-700 shadow-md m-10 rounded px-8 pt-6 pb-8 mb-4" method="post">
      {% csrf_token %}
      <div class="mb-2">
        <label class="block text-gray-700 text-sm font-bold mb-2"> Username</label>
        <p class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">{{ form.username }}</p>
        <label class="block text-gray-700 text-sm font-bold mb-2">Password</label>
        <p class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">{{ form.password }}</p>
      </div>
      <button class="bg-green-500 text-white px-5 py-2" type="submit">Log In</button>
      <button class="bg-green-500 text-white px-5 py-2"><a href="{% url 'users:register' %}">Register</a></button>
    </form>
  </div>
{% endblock content %}

mysite/users/templates/users/logout.html
<form action="{% url 'users:logout' %}" method="POST">
      {% csrf_token %}
      <button type="submit">LogOut</button>
</form>

mysite/users/templates/users/profile.html
{% extends "myapp/base.html" %}

{% block content %}

    {% if user.profile %}
    <div class="grid p-10 grid-cols-1 lg:grid-cols-3 sm:grid-cols-1">
        <div class="rounded shadow-lg">
            <div>
                {% if user.profile.image %}
                    <img src="{{ user.profile.image.url }}">
                {% endif %}
            </div>
            <h1 class="font-bold text-xl m-2">{{ user.username }}</h1>
        </div>
    </div>
    {% else %}
        <h1>Form profile</h1>
        <form method="post">

        </form>
    {% endif %}


{% endblock content %}

mysite/users/templates/users/register.html
{% extends "myapp/base.html" %}

{% block content %}
    <div class="container py-5">
        <h1 class="text-2xl m-10 font-bold">Register User</h1>
        <form class="w-2/5 bg-white-700 shadow-md m-10 rounded px-8 pt-6 pb-8 mb-4" method="post">
            {% csrf_token %}
            <div class="mb-2">
                <label class="block text-gray-700 text-sm font-bold mb-2">Username</label>
                <p class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">{{form.username}}</p>
                <label class="block text-gray-700 text-sm font-bold mt-5 mb-2">Email</label>
                <p class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">{{form.email}}</p>
                <label class="block text-gray-700 text-sm font-bold mt-5 mb-2">Password</label>
                <p class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">{{form.password1}}</p>
                <label class="block text-gray-700 text-sm font-bold mt-5 mb-2">Confirm Password</label>
                <p class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">{{form.password2}}</p>
            </div>
            <button class="bg-green-500 text-white px-5 py-2" type="submit">Register</button>
        </form>
    </div>

{% endblock content %}